name: Glitch.com 

on:
  push:
    branches: [ master ]

jobs:
  push:
    runs-on: [ubuntu-latest]
    steps:
      - uses: glitch-tools/sync-glitch-github-action@master
      - with: 
          GLITCH_TOKEN: ${{ secrets.GLITCH_TOKEN }}
          GLITCH_PROJECT_ID: ${{ secrets.GLITCH_TOKEN }}

